apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
  volumes:
  - name: empty-dir
    emptyDir: {}